from __future__ import annotations


ENTROPY_CAP = 3
ENERGY_CAP = 3
LOCAL_CAP = 3
NEG_CAP = 6
LOCAL_CENTERS = 3

FIXED_ALPHA_G = 4.0
FIXED_ALPHA_L = 3.5
FIXED_ALPHA_N = 0.14

TEXT_SCORE_WEIGHT = 0.15
ZERO_SHOT_PROMPT_SOURCE = "manual_full"
TEXT_DISTRIBUTION_PROMPT_SOURCE = "manualfull_llm_dynamic_init"
DIST_EPS = 1e-4
DIST_MIN_VAR = 1e-4
TEXT_DIST_EPS = 1e-4
TEXT_DIST_MIN_VAR = 1e-4

SCORE_NORM_MODE = "running_zscore"
SCORE_NORM_MIN_COUNT = 8
SCORE_NORM_EPS = 1e-6
SCORE_NORM_CLIP = 0.0

